### ISSUE TITLE
Authentication Does not work when enable security globally to all operations . Seems to be a bug

### ISSUE THREAD

**Issue by sachinda123456** [grinat/moleculer-auto-openapi#10]
According to moleculer-auto-openapi sample , defined  openapi service . But I need a bearer token for each request . But the `moleculer-auto-openapi` sample document does not mention how to apply each request . After  looks at swagger documentation there is a key called security .Then I added a security key to my script . see code below . Then each request authorization symbol is displayed . But the UI console indicates some undefined error . It seems to be bug of `moleculer-auto-openapi` Or any method to achieve my requirement 

```
`module.exports = {
  name: 'openapi',
  mixins: [Openapi],
  settings: {
    // all setting optional
    openapi: {
      openapi: '3.0.0',
      info: {
        // about project
        description: 'task budy',
        title: 'Back end'
      },
      tags: [
        // you tags
        { name: 'auth', description: 'My custom name' }
      ],
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT'
          }

        }
      },
      security: {
        bearerAuth: []
      }
    }
  }
}`
```
![Screenshot 2021-09-22 at 16 47 56](https://user-images.githubusercontent.com/33275897/134339332-7138ddd0-a2c9-407a-b2b0-cd34c7c06e33.png)

**Comment by grinat** [comment]
@sachinda123456 security is a array
```js
security: [ { bearerAuth: [] }],
```

**Comment by sachinda123456** [comment]
> @sachinda123456 security is a array
> 
> ```js
> security: [ { bearerAuth: [] }],
> ```
> 
> see docs: https://swagger.io/docs/specification/authentication/
> 
> ```yaml
> security:
>   - OAuth2:
>       - scope1
>       - scope2
>   - OpenId:
>       - scopeA
>       - scopeB
>   - BasicAuth: []
> ```
same result no change

**Comment by grinat** [comment]
@sachinda123456 are you changed security to array and do not change components? Correct 100% worked example:
![b7VxK2k](https://user-images.githubusercontent.com/16123366/135259627-a1b3fb55-0ca0-4ec7-be2e-6b1033c8bcde.png)

**Comment by sachinda123456** [comment]
> @sachinda123456 are you changed security to array and do not change components? Correct 100% worked example: ![b7VxK2k](https://user-images.githubusercontent.com/16123366/1352596
![Screenshot 2021-09-29 at 17 11 29](https://user-images.githubusercontent.com/33275897/135261619-4cd8d40e-c9be-4db7-8df7-88ed9731e042.png)
27-a1b3fb55-0ca0-4ec7-be2e-6b1033c8bcde.png)
> 
> ```ts
>       security: [ { cookieAuth: [] }],
>       components: {
>         securitySchemes: {
>           cookieAuth: {
>             type: `apiKey`,
>             in: `cookie`,
>             name: `name`,
>           },
>         },
>       },
> ```

see my code thats not work for me

**Comment by grinat** [comment]
@sachinda123456 check the moleculer-auto-openapi version is latest, check you correct added openapi service, check you realy reloaded services and clean cache in browser and etc. Its problem of your enviroment, not a library.
