### ISSUE TITLE
moleculer-web + NATS = "NATS error. 'Maximum Payload Violation'"

### ISSUE THREAD

**Issue by jodysimpson** [grinat/moleculer-auto-openapi#15]
If you use [moleculerjs/moleculer-web](https://github.com/moleculerjs/moleculer-web) with NATS set as the transporter,  this will cause a `NATS error. 'Maximum Payload Violation'` error with the default NATS settings.  This occurs when transferring the assets because the default NATS message limit is 1MB and some of the assets exceed this limit.

This can be resolved either by increasing the NATS message limit (not ideal) or returning the assets back to moleculer-web as a stream.

**Comment by grinat** [comment]
@jodysimpson fixed in moleculer-auto-openapi@1.1.4
