### ISSUE TITLE
Refused to execute inline script because it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by 1fabiopereira** [grinat/moleculer-auto-openapi#17]
I have the following error when I try to load UI.

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-Uyj7FQr0e7NFvyKGaY4fjUmqENQjqqM1AnQ62UyrBAs='), or a nonce ('nonce-...') is required to enable inline execution.`

![image](https://user-images.githubusercontent.com/11349795/183244628-3cf34ea2-ea40-4627-858b-891d78bcb854.png)

**Comment by grinat** [comment]
You can ovveride action ui and past needed hash or any header or data or etc, see: https://github.com/grinat/moleculer-auto-openapi/blob/50ae0bf3161938905d505dd5302801f16ed61562/index.js#L290
