### ISSUE TITLE
Type Error when using open api

### ISSUE THREAD

**Issue by khoathuc** [grinat/moleculer-auto-openapi#20]
I have a Type Error when apply openapi in my moleculer project.
![image](https://user-images.githubusercontent.com/85089328/193730389-dbd13fef-f48e-4fd1-9001-e02dbefcde25.png)
In my case, type of shortDefinition is not string, so i met typeError( shortDefinition.split('|') is not a funtion) 
So i must convert shortDefition into string using shortDefinition.toString(). It work for me.

**Comment by rdegaris** [comment]
Another possibility for this:

if (shortDefinition.type !== "array") {
   return node;
}
