### ISSUE TITLE
No authorization header

### ISSUE THREAD

**Issue by jdavault** [grinat/moleculer-auto-openapi#22]
I'm able to change securitySchmes in the openapi.service file and I can entry different option "Basic", "Bearer", "ApiKey", etc and all look act normal but when I submit on of the SWAG calls .. there is never any header added .. has anyone else run into this.  Everything is working fine .. just not getting this auth header

**Comment by YuanLinMtp** [comment]
same situation for me too with this configuration...

components: {
	securitySchemes: {
		bearerAuth: {
			type: 'http',
			scheme: 'bearer',
			bearerFormat: 'JWT',
		},
	},
},

**Comment by grinat** [comment]
@YuanLinMtp @jdavault 

Example for moleculer-auto-openapi=1.1.5

```ts
const OpenapiService: ServiceSchema = {
  name: `openapi`,
  settings: {
    openapi: {
      security: [ 
        { bearerAuth: [] },
        { cookieAuth: [] },
      ],
      components: {
        securitySchemes: {
          cookieAuth: {
            type: `apiKey`,
            in: `cookie`,
            name: `myCookie`,
          },
          bearerAuth: {
            type: `http`,
            scheme: `bearer`,
            bearerFormat: `JWT`,
          },
        },
      },
    },
  },
};

export default OpenapiService;
```

Result:
![image](https://github.com/grinat/moleculer-auto-openapi/assets/16123366/9de39712-e898-4ca6-8dc3-f854632d2276)


More info at: https://swagger.io/docs/specification/authentication/
