### ISSUE TITLE
common responses object is not exchangable

### ISSUE THREAD

**Issue by hkess** [grinat/moleculer-auto-openapi#4]
I would like to pass custom common responses through the settings in the openapi service.
Currently i would have to overwide my custom common responses object as the value from responses inside the module:
```
doc.paths[openapiPath][method] = {
            summary: "",
            tags: [service],
            // rawParams: params,
            parameters: [...queryParams],
            responses: {
              // attach common responses
              200: {
                $ref: "#/components/responses/ReturnedData",
              },
              401: {
                $ref: "#/components/responses/UnauthorizedError",
              },
              422: {
                $ref: "#/components/responses/ValidationError",
              },
              default: {
                $ref: "#/components/responses/ServerError",
              },
            },
          }
```

**Comment by grinat** [comment]
@hkess added in v1.0.8 you can replace in settings.commonPathItemObjectResponses
![Снимок экрана от 2021-09-14 13-28-07](https://user-images.githubusercontent.com/16123366/133241750-3fa7c1de-e27a-4357-b1d5-9cc1f40d01bb.png)

multipart/stream default response can replace in methods.getFileContentRequestBodyScheme
